import Head from "next/head";
import Image from "next/image";
import CoinBoxContainer from "../components/coin/coinBoxContainer";
import CoinCard from "../components/coin/CoinCart";
import CoindetailsDesktop from "../components/coin/CoindetailsDesktop";
import CoinDetailsMobile from "../components/coin/CoinDetailsMobile";
import Header from "../components/modules/Header";
import SearchBox from "../components/modules/SearchBox";
import SIdeNavbar from "../components/modules/SIdeNavbar";
import styles from "../styles/Home.module.css";
import tests from "../components/tests";
import HomeTemplate from "../components/HomeTemplate";
import CoindetailsList from "../components/coin/CoindetailsList";
import { useEffect } from "react";
import axios from "axios";
import { useDispatch, useSelector } from "react-redux";
import { getAllCoinsReq } from "../Redux/Slices/coins/getCoinsSlice";

export default function Home() {
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(getAllCoinsReq());
  }, []);

  const coins = useSelector((state) => state.coins);
  console.log(coins);

  return (
    <div className="mb-[500px] relative  ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {/* <SearchBox /> */}
      <div className="max-w-7xl mx-auto px-2">
        <HomeTemplate />

        {/* <CoinBoxContainer />
        <CoinDetailsMobile />
        <CoindetailsDesktop /> */}
      </div>
      {/* <SIdeNavbar /> */}
    </div>
  );
}
